[package]
name = "urlharvest"
version = "0.6.9"
authors = ["Sami J. Mäkinen <sjm@iki.fi>"]
description = "URL harvester for IRC irssi logs, no bot"
repository = "https://github.com/sjm42/urlharvest-rs"
readme = "README.md"
keywords = ["irc", "url", "harvest", "irssi", "search"]
license = "MIT OR Apache-2.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
chrono = "0.4"
enum-iterator = "1.2"
env_logger = "0.9"
futures = "0.3"
handlebars = "4.3"
itertools = "0.10"
linemux = "0.2.4"
# linemux = { path = "../linemux" }
# linemux = { git = "https://github.com/sjm42/linemux" }
log = "0.4"
regex = "1.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shellexpand = "2.1"
sqlx = { version = "0.6", features = [
  "macros",
  "migrate",
  "runtime-tokio-native-tls",
  "sqlite",
  "offline",
] }
structopt = "0.3"
tera = "1.17"
tokio = { version = "1.21", features = ["full"] }
url = "2.3"
warp = "0.3"
webpage = "1.4"

[build-dependencies]
build-data = "0.1"

[profile.release]
lto = true
opt-level = 3 #default
# opt-level = 'z'  # Optimize for size.

# EOF
