[package]
name = "urlharvest"
version = "0.5.1"
authors = ["Sami J. Mäkinen <sjm@iki.fi>"]
description = "URL harvester for IRC irssi logs, no bot"
repository = "https://github.com/sjm42/urlharvest-rs"
readme = "README.md"
keywords = ["irc", "url", "harvest", "irssi", "search"]
license = "MIT OR Apache-2.0"
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
env_logger = "0.9"
handlebars = "4.1"
libsqlite3-sys = "0"
linemux = "0.2"
log = "0.4"
regex = "1.5"
rusqlite = "0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.3"
tera = "1.12"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
webpage = "1.3"

[build-dependencies]
build-data = "0.1"

[profile.release]
lto = true
opt-level = 3 #default
# opt-level = 'z'  # Optimize for size.

# EOF
