[package]
name = "irssi-urlharvest"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "*"
linemux = "*"
log = "*"
regex = "*"
structopt = "*"
tokio = { version = "*", features = ["full"] }

[build-dependencies]
build-data = "*"

[profile.release]
lto = true
opt-level = 3 #default
# opt-level = 'z'  # Optimize for size.

# EOF
