[package]
name = "urlharvest"
version = "0.4.0"
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "*"
env_logger = "*"
handlebars = "*"
libsqlite3-sys = "*"
linemux = "*"
log = "*"
regex = "*"
rusqlite = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
structopt = "*"
tera = "*"
tokio = { version = "*", features = ["full"] }
warp = "*"
webpage = "*"

[build-dependencies]
build-data = "*"

[profile.release]
lto = true
opt-level = 3 #default
# opt-level = 'z'  # Optimize for size.

# EOF
