# Cargo.toml

[package]
name = "urlharvest"
version = "1.0.3"
authors = ["Sami J. Mäkinen <sjm@iki.fi>"]
description = "URL harvester for IRC irssi logs, no bot"
repository = "https://github.com/sjm42/urlharvest-rs"
readme = "README.md"
keywords = ["irc", "url", "harvest", "irssi", "search"]
license = "MIT OR Apache-2.0"
edition = "2021"
resolver = "2"


[dependencies]
anyhow = "1.0"
chrono = "0.4"
enum-iterator = "1.4"
env_logger = "0.10"
futures = "0.3"
handlebars = "4.3"
itertools = "0.11"
linemux = "0.3"
log = "0.4"
regex = "1.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shellexpand = { version = "3.1", features = ["full"] }
sqlx = { version = "0.6", features = [
  "macros",
  "migrate",
  "runtime-tokio-native-tls",
  "sqlite",
  "offline",
] }
structopt = "0.3"
tera = "1.19"
tokio = { version = "1.29", features = ["full"] }
url = "2.4"
warp = "0.3"
webpage = "1.6"


[build-dependencies]
build-data = "0.1"


[profile.release]
lto = true
opt-level = "s" # static
# opt-level = 3 # default
# opt-level = 'z'  # Optimize for size.

# EOF
